### ISSUE TITLE
Why has the README added a link to a version of this that phones-home to a sketchy site?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [puffnfresh/Honer.app#18]
Upon "upgrading" to the executable linked in the README (no source-code? no website?),

<img width="816" alt="Screen Shot 2020-06-21 at 14 48 50" src="https://user-images.githubusercontent.com/200/85233766-80936680-b3ce-11ea-9f0a-717353e8188b.png">

Uh, yikes, no. Visiting the domain reported references that sketchy "CleanMyMac" app, to boot.

**Comment by amad** [comment]
Yeah it's sketchy.

You can download the last release or even compile it.
https://github.com/puffnfresh/Honer.app/releases

Someone claimed that he made a modern version, and unfortunately author agreed (https://github.com/puffnfresh/Honer.app/pull/15) to add it to the readme.

I don't see any changes on his fork: https://github.com/paganel/Honer.app, nor a good explanation https://github.com/puffnfresh/Honer.app/issues/16.

**Comment by puffnfresh** [comment]
Yeah I agree, it's all dodgy but a few people asked for this version to be referenced. I'm not maintaining so this is where we're at. I'd love to see the code and "no until the code is ready" is pretty disappointing.

**Comment by puffnfresh** [comment]
@paganel is the code ready?

**Comment by asyncee** [comment]
Links to third-party binaries always introduce security risk. This is common attack vector on github.

**Comment by koekeishiya** [comment]
This was brought to my attention and so I figured I would reply with solutions that I made in the past.
I initially had window borders for both active and inactive windows in yabai (tiling window manager for macOS), but I removed the system and made a separate application for it, because it has various issues such as delayed movement, and some issues with topmost windows etc (window ordering). It is fairly usable though, and works more or less the same way as the old Honer did, but more sophisticated infrastructure for tracking windows (because of inactive window borders). You can find this here (open source): https://github.com/koekeishiya/limelight

There is also an older tag from before I did the port, which was supposed to be a sample showing how to generate a border for the focused window only. See this tag: https://github.com/koekeishiya/limelight/tree/focused_border_only

**NOTE**: I do NOT maintain any of these versions anymore. Code is MIT license if anyone here is interested in building on it.

**Comment by asyncee** [comment]
I can approve that limelight is working perfectly.

**Comment by puffnfresh** [comment]
Removed the sketchy app and added a link to Limelight instead.
